apiVersion: v1
kind: Secret
metadata:
  name: ams-secrets
  namespace: apartment-system
type: Opaque
stringData:
  PG_PASSWORD: "X9CaB/Uh6hkQ76D3ChV+KKHkvsyutUk4"
  JWT_SECRET: "crxHUKZh30p0gbzaMyuwB0ltcM9AWOa7Bln0SyD/IkeJRcwIWBG3MsqnLl68wWAC"
  CLIENT_URL: "http://18.217.205.192"
  MONGO_URI: "mongodb://mongo:27017/apartment_docs"
